package com.kdroid.filter;
import android.app.*;import android.content.*;import android.content.pm.*;import android.text.InputType;import android.widget.*;import java.util.*;
public class AdminActivity extends Activity{LinearLayout l;int fails=0;long blockedUntil=0;protected void onCreate(android.os.Bundle b){super.onCreate(b);login();}
 void login(){l=UI.root(this,"כניסת מנהל");l.addView(UI.note(this,"הזן את הקוד שקבעת בהגדרה הראשונית"));EditText p=new EditText(this);p.setHint("קוד מנהל");p.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_VARIATION_PASSWORD);l.addView(p);Button x=UI.b(this,"כניסה");x.setOnClickListener(v->{if(System.currentTimeMillis()<blockedUntil){UI.msg(this,"נסה שוב בעוד מספר שניות");return;}if(Prefs.pin(this,p.getText().toString())){fails=0;menu();}else{fails++;if(fails>=5){blockedUntil=System.currentTimeMillis()+30000;fails=0;}UI.msg(this,"קוד שגוי");}});l.addView(x);}
 void menu(){l=UI.root(this,"מנהל");Button m=UI.b(this,"ניהול והגבלות");m.setOnClickListener(v->manage());l.addView(m);Button apps=UI.b(this,"אפליקציות ואפליקציה ראשית");apps.setOnClickListener(v->apps());l.addView(apps);Button cp=UI.b(this,"שינוי קוד מנהל");cp.setOnClickListener(v->changePin());l.addView(cp);Button t=UI.b(this,"הפעל מצב תחזוקה");t.setOnClickListener(v->{Policy.maintenance(this,true);try{stopLockTask();}catch(Exception ignored){}UI.msg(this,"מצב תחזוקה פעיל — חזור לכאן כדי לסיים");});l.addView(t);Button lock=UI.b(this,"סיום תחזוקה ונעילה");lock.setOnClickListener(v->{Policy.maintenance(this,false);startActivity(new Intent(this,MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP));finish();});l.addView(lock);Button rm=UI.b(this,"הסר ניהול והכן להסרת האפליקציה");rm.setOnClickListener(v->confirmRemove());l.addView(rm);}
 void manage(){l=UI.root(this,"ניהול והגבלות");opt("חסום איפוס להגדרות יצרן","reset",true);opt("חסום מצב בטוח","safe",true);opt("חסום ADB / אפשרויות מפתחים","adb",false);opt("חסום התקנה ממקורות לא ידועים","install",true);opt("חסום הסרת אפליקציות","uninstall",true);opt("חסום הוספת משתמשים","users",true);opt("חסום שורת מצב והתראות","status",true);Button save=UI.b(this,"שמור והחל מדיניות");save.setOnClickListener(v->{Policy.apply(this,Prefs.main(this));UI.msg(this,"ההגדרות נשמרו");});l.addView(save);}
 void opt(String label,String key,boolean def){Switch s=UI.sw(this,label,Prefs.opt(this,key,def));s.setOnCheckedChangeListener((v,on)->Prefs.setOpt(this,key,on));l.addView(s);}
 void apps(){l=UI.root(this,"אפליקציות");l.addView(UI.note(this,"לחיצה על שם האפליקציה הופכת אותה לראשית. המתג חוסם/מחזיר אפליקציה."));PackageManager pm=getPackageManager();Intent q=new Intent(Intent.ACTION_MAIN).addCategory(Intent.CATEGORY_LAUNCHER);Set<String>seen=new HashSet<>();for(ResolveInfo r:pm.queryIntentActivities(q,PackageManager.MATCH_DISABLED_COMPONENTS)){String pkg=r.activityInfo.packageName;if(!seen.add(pkg)||pkg.equals(getPackageName()))continue;LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);Button b=UI.b(this,r.loadLabel(pm)+"
"+pkg);b.setOnClickListener(v->{Policy.setBlocked(this,pkg,false);Prefs.main(this,pkg);Policy.apply(this,pkg);UI.msg(this,"האפליקציה הראשית שונתה");});row.addView(b,new LinearLayout.LayoutParams(0,-2,1));Switch sw=new Switch(this);sw.setText("חסום");sw.setChecked(Prefs.blocked(this).contains(pkg));sw.setEnabled(!Policy.isProtected(this,pkg));sw.setOnCheckedChangeListener((v,on)->Policy.setBlocked(this,pkg,on));row.addView(sw);l.addView(row);}}
 void changePin(){l=UI.root(this,"שינוי קוד מנהל");EditText p=new EditText(this);p.setHint("קוד חדש – לפחות 4 ספרות");p.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_VARIATION_PASSWORD);l.addView(p);EditText p2=new EditText(this);p2.setHint("אימות הקוד החדש");p2.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_VARIATION_PASSWORD);l.addView(p2);Button b=UI.b(this,"שמור קוד חדש");b.setOnClickListener(v->{if(p.getText().length()<4){UI.msg(this,"לפחות 4 ספרות");return;}if(!p.getText().toString().equals(p2.getText().toString())){UI.msg(this,"הקודים אינם זהים");return;}Prefs.changePin(this,p.getText().toString());UI.msg(this,"הקוד שונה");menu();});l.addView(b);}
 void confirmRemove(){new AlertDialog.Builder(this).setTitle("הסרת KioskMDM").setMessage("הפעולה תסיר את הרשאת Device Owner ותאפשר להסיר את האפליקציה. להמשיך?").setNegativeButton("ביטול",null).setPositiveButton("הסר ניהול",(d,w)->{try{stopLockTask();}catch(Exception ignored){}Policy.removeOwner(this);UI.msg(this,"הניהול הוסר. כעת ניתן להסיר את KioskMDM.");}).show();}
}