package com.kioskmdm;
import android.app.admin.*; import android.content.*; import android.os.*; import java.util.*;
public final class Policy {
 static ComponentName cn(Context c){return new ComponentName(c,AdminReceiver.class);} static DevicePolicyManager d(Context c){return (DevicePolicyManager)c.getSystemService(Context.DEVICE_POLICY_SERVICE);} static boolean owner(Context c){return d(c).isDeviceOwnerApp(c.getPackageName());}
 static String[] restrictions(){return new String[]{UserManager.DISALLOW_FACTORY_RESET,UserManager.DISALLOW_SAFE_BOOT,UserManager.DISALLOW_DEBUGGING_FEATURES,UserManager.DISALLOW_INSTALL_UNKNOWN_SOURCES,UserManager.DISALLOW_UNINSTALL_APPS,UserManager.DISALLOW_ADD_USER};}
 static void apply(Context c,String main){if(!owner(c))return; DevicePolicyManager m=d(c); ComponentName a=cn(c); Prefs.maintenance(c,false); for(String x:restrictions())try{m.addUserRestriction(a,x);}catch(Exception ignored){} try{m.setStatusBarDisabled(a,true);}catch(Exception ignored){} try{m.setLockTaskPackages(a,new String[]{c.getPackageName(),main});}catch(Exception ignored){} applyBlocked(c); }
 static void applyBlocked(Context c){if(!owner(c))return;DevicePolicyManager m=d(c);ComponentName a=cn(c);Set<String> wanted=Prefs.blocked(c); for(String pkg:wanted){if(isProtected(c,pkg))continue;try{m.setApplicationHidden(a,pkg,true);}catch(Exception ignored){}}}
 static void setBlocked(Context c,String pkg,boolean blocked){if(!owner(c)||isProtected(c,pkg))return;DevicePolicyManager m=d(c);try{m.setApplicationHidden(cn(c),pkg,blocked);Set<String>s=Prefs.blocked(c);if(blocked)s.add(pkg);else s.remove(pkg);Prefs.blocked(c,s);}catch(Exception ignored){}}
 static boolean isProtected(Context c,String pkg){return pkg.equals(c.getPackageName())||pkg.equals(Prefs.main(c))||pkg.equals("com.android.systemui")||pkg.equals("android")||pkg.equals("com.android.settings")||pkg.equals("com.google.android.packageinstaller")||pkg.contains("permissioncontroller")||pkg.contains("packageinstaller");}
 static void maintenance(Context c,boolean on){if(!owner(c))return;DevicePolicyManager m=d(c);ComponentName a=cn(c);Prefs.maintenance(c,on);if(on){try{m.setStatusBarDisabled(a,false);}catch(Exception ignored){}for(String x:restrictions())try{m.clearUserRestriction(a,x);}catch(Exception ignored){}try{m.setLockTaskPackages(a,new String[]{});}catch(Exception ignored){}}else apply(c,Prefs.main(c));}
}