package com.kioskmdm;
import android.app.*;import android.content.*;import android.graphics.Color;import android.graphics.drawable.GradientDrawable;import android.view.*;import android.widget.*;
public final class UI{
 static int dp(Context c,int n){return(int)(n*c.getResources().getDisplayMetrics().density+.5f);}
 static GradientDrawable bg(int color,float radius){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(radius);return g;}
 static LinearLayout root(Activity a,String title){a.getWindow().setStatusBarColor(Color.rgb(15,35,70));ScrollView s=new ScrollView(a);s.setFillViewport(true);LinearLayout l=new LinearLayout(a);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(dp(a,20),dp(a,24),dp(a,20),dp(a,32));l.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);l.setBackgroundColor(Color.rgb(245,247,251));TextView t=new TextView(a);t.setText(title);t.setTextSize(27);t.setTextColor(Color.rgb(18,43,82));t.setGravity(Gravity.RIGHT);t.setPadding(dp(a,4),0,dp(a,4),dp(a,20));l.addView(t);s.addView(l);a.setContentView(s);return l;}
 static Button b(Activity a,String s){Button b=new Button(a);b.setText(s);b.setTextSize(16);b.setTextColor(Color.WHITE);b.setAllCaps(false);b.setGravity(Gravity.CENTER);b.setBackground(bg(Color.rgb(31,91,190),dp(a,14)));b.setElevation(dp(a,2));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(a,56));p.setMargins(0,dp(a,7),0,dp(a,7));b.setLayoutParams(p);return b;}
 static Switch sw(Activity a,String s,boolean on){Switch v=new Switch(a);v.setText(s);v.setTextSize(16);v.setTextColor(Color.rgb(30,40,55));v.setChecked(on);v.setGravity(Gravity.CENTER_VERTICAL);v.setPadding(dp(a,16),dp(a,14),dp(a,16),dp(a,14));v.setBackground(bg(Color.WHITE,dp(a,14)));v.setElevation(dp(a,1));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(a,5),0,dp(a,5));v.setLayoutParams(p);return v;}
 static TextView note(Activity a,String s){TextView v=new TextView(a);v.setText(s);v.setTextSize(14);v.setTextColor(Color.rgb(85,95,110));v.setGravity(Gravity.RIGHT);v.setPadding(dp(a,4),dp(a,8),dp(a,4),dp(a,10));return v;}
 static void msg(Context c,String s){Toast.makeText(c,s,Toast.LENGTH_SHORT).show();}
}